### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by lpinca** [faye/faye-websocket-node#38]
Commit d2abdb1870692b509bf6aab7e043326b58d1caeb introduced a regression.
Under certain conditions, a connection cannot be closed correctly.
Consider the following example:
```js
'use strict';

var Faye = require('faye-websocket')
  , http = require('http')
  , client;

var server = http.createServer();

server.on('upgrade', function upgrade(req, socket, head) {
  if (!Faye.isWebSocket(req)) return socket.destroy();

  var ws = new Faye(req, socket, head);

  ws.on('open', function open() {
    server.close();
    client.close();
  });

  ws.on('close', function close(evt) {
    console.log('server close', evt.code, evt.reason);
  });
});

server.listen(3000, function listening() {
  client = new Faye.Client('ws://localhost:3000/');

  client.on('close', function close(evt) {
    console.log('client close', evt.code, evt.reason);
  });
});
```
The expected result is:
```sh
macbook:regression luigi$ node server.js
client close 1000 
server close 1006 
macbook:regression luigi$
```
The actual result is:
```sh
macbook:regression luigi$ node server.js
server close 1006
```
As you can see, the process does not exits.

The problem seems to be caused by the fact that [`_finalizeClose()`](https://github.com/faye/faye-websocket-node/blob/cd8f337278954d89709788ca3e63473597e372b2/lib/faye/websocket/api.js#L156-L171) does not call `end()` on the stream and `_beginClose()` is never called on the server because we don't receive a Close control frame as the connection is closed before the client is fully opened.

**Comment by lpinca** [comment]
A monkey patch to fix the issue is this:
```diff
diff --git a/lib/faye/websocket/api.js b/lib/faye/websocket/api.js
index 4316340..9ee9edd 100644
--- a/lib/faye/websocket/api.js
+++ b/lib/faye/websocket/api.js
@@ -32,7 +32,7 @@ var API = function(options) {
 
   this._driver.on('open',    function(e) { self._open() });
   this._driver.on('message', function(e) { self._receiveMessage(e.data) });
-  this._driver.on('close',   function(e) { self._beginClose(e.reason, e.code) });
+  this._driver.once('close',   function(e) { self._beginClose(e.reason, e.code) });
 
   this._driver.on('error', function(error) {
     self._emitError(error.message);
@@ -158,6 +158,8 @@ var instance = {
     this.readyState = API.CLOSED;
 
     if (this._pingTimer) clearInterval(this._pingTimer);
+    if (this._stream) this._stream.end();
+
     if (this.readable) this.emit('end');
     this.readable = this.writable = false;
```
but i will not send a pull request, because there must be a better way to solve the problem.

**Comment by suprememoocow** [comment]
I'm seeing the same problem with 0.9.2, which resulted in a large number of open connections on our servers. Until it's fixed, I'm going to revert to 0.9.1, which doesn't seem to exhibit the same behaviour.

![Datadog](http://cl.ly/image/253W022b3507/Image%202015-02-11%20at%204.40.39%20pm.png)

**Comment by jcoglan** [comment]
Your example works correctly after applying https://github.com/faye/websocket-driver-node/commit/daa37974c667484e7a4aeb55d0198ce4ffebe07d and https://github.com/faye/faye-websocket-node/commit/e9daa1d55e68cb43b7caa2b4da9288cdd5130021

**Comment by lpinca** [comment]
@jcoglan there is still an issue.
If you apply the following patch to my original test case
```diff
diff --git a/index.js b/index.js
index bb7817d..50aa269 100644
--- a/index.js
+++ b/index.js
@@ -14,6 +14,7 @@ server.on('upgrade', function upgrade(req, socket, head) {
   ws.on('open', function open() {
     server.close();
     client.close();
+    ws.send('foo');
   });
 
   ws.on('close', function close(evt) {
```
and run the test, the following error is thrown:
```sh
luigi@ubuntu:~/test$ node index.js 
/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133
    this._pipeline.processIncomingMessage(message, callback, context);
                  ^
TypeError: Cannot read property 'processIncomingMessage' of undefined
    at instance.processIncomingMessage (/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:19)
    at instance._emitMessage (/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at instance._emitFrame (/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at instance.parse (/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at instance.parse (/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/home/luigi/test/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

**Comment by jcoglan** [comment]
@lpinca This is fixed in https://github.com/faye/websocket-driver-node/commit/23d0a9ea5e4906155649f5106a689a884a875d7d

**Comment by lpinca** [comment]
Thank you. :+1:
